name: FastAPI CI/CD

on:
  # Trigger the workflow on push
  push:
    branches:
      # Push events on main branch
      - main

jobs:

  CI:
    # Define the runner used in the workflow
    runs-on: ubuntu-latest
    steps:
      # Check out repo so our workflow can access it
      - uses: actions/checkout@v2

      # Step-1 Setup Python
      - name: Set up Python
        # This action sets up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          # optional: achitecture: (x64) or x86
          #
      # Step-2 Install Python virtualenv
      - name: Install Python Virtualenv
        run: pip3 install virtualenv

      # Step-3 Setup Virtualenv
      - name: Virtualenv
        uses: actions/cache@v2
        id: cache-venv # Name for referring later
        with:
          path: venv # What we cache: the virtual env
          # The cache key depends on requirements.txt
        key: ${{ runner.os  }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: /
          ${{ runner.os }}-venv-

      # Step-4 Build a Virtualenv, but only if it does not exist already
      - name: Activate Virtualenv
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run Tests
        # Note that we have to activate the virtualenv every time
        # Because Github actions doesn't preserve the environement
        run: . venv/bin/activate && pytest
      - name: Create archive of dependencies
        run: /
          cd ./venv/lib/python3.10/site-packages
          zip -r9 ../../../../api.zip .
      - name: Add API files to zip file
        run: cd ./api && zip -f ../api.zip -r .
      - name: Upload zip file artifact
        # uploads artifacts from your workflow allowing you to share data between jobs
        # Stores data once a workflow is complete
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip



